#!/usr/bin/env python3
"""Regenerate .github/workflows/release.yml from `maturin generate-ci`.

Maturin owns the shape of the release pipeline; this script re-applies the
small set of project-specific tweaks after every regeneration, so updating
CI is "run one command, review the diff" instead of a risky manual merge:

  1. Trigger only on `v*` tags (plus manual dispatch for dry runs).
  2. Drop maturin's generated `test` job — tests live in test.yml.
  3. Rewrite the absolute manifest path maturin embeds back to a relative
     repo path, so the workflow is portable.
  4. Append the custom `publish-crates` job (crates.io publishing), which
     upstream maturin does not generate.
  5. Rename the workflow to "Release" (tests live in test.yml).

Usage:
    ./scripts/regenerate-release-ci.py

Requires maturin on PATH (e.g. `pip install maturin`). After running,
review the diff of .github/workflows/release.yml before committing —
upstream maturin changes will show up there.
"""

import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / "py/partial-json-fixer/Cargo.toml"
REL_MANIFEST = "py/partial-json-fixer/Cargo.toml"
OUT = REPO_ROOT / ".github/workflows/release.yml"

HEADER = """\
# Generated by scripts/regenerate-release-ci.py (maturin generate-ci + project tweaks) — do not edit by hand.
# To change this file, edit the script and re-run it, then review the diff.
"""

TRIGGER = """\
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
"""

PUBLISH_CRATES = """\
  publish-crates:
    name: Publish Rust crate to crates.io
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish core crate
        run: cargo publish --manifest-path crates/partial-json-fixer/Cargo.toml
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
"""


def main() -> int:
    subprocess.run(["maturin", "--version"], check=True, capture_output=True)

    # maturin 1.14+ prints the workflow to stdout by default; older versions
    # wrote .github/workflows/CI.yml. Handle both so either version works.
    with tempfile.TemporaryDirectory() as tmp:
        tmpdir = Path(tmp)
        # generate-ci expects a git repo when writing files directly.
        subprocess.run(["git", "init", "-q"], cwd=tmpdir, check=True)
        proc = subprocess.run(
            ["maturin", "generate-ci", "-m", str(MANIFEST), "github"],
            cwd=tmpdir,
            check=True,
            capture_output=True,
            text=True,
        )
        text = proc.stdout.strip("\n")
        if "name: CI" not in text:
            generated = tmpdir / ".github/workflows/CI.yml"
            if not generated.exists():
                print("error: could not locate maturin's generated workflow", file=sys.stderr)
                return 1
            text = generated.read_text()

    # Replace the autogenerated header.
    text = HEADER + text[text.index("name: "):]

    # 1. Tag-only trigger (+ manual dispatch).
    start = text.index("\non:")
    end = text.index("\npermissions:", start)
    text = text[:start] + "\n" + TRIGGER + text[end:]

    # 2. Drop the generated `test` job (everything from its key to the next
    # sibling job key at the same indentation level). maturin >= 1.14 no
    # longer generates one; keep this for older versions.
    text, n = re.subn(r"(?ms)^  test:\n.*?(?=^  \w)", "", text)
    if n > 1:
        print(f"error: expected at most one `test` job, found {n}", file=sys.stderr)
        return 1

    # 3. Make manifest paths relative/portable again.
    text = text.replace(str(MANIFEST) + " ", REL_MANIFEST + " ")
    text = text.replace(str(MANIFEST), REL_MANIFEST)

    # 4. crates.io publishing is project-specific; append it.
    text = text.rstrip("\n") + "\n\n" + PUBLISH_CRATES

    # 5. Distinguish from the hand-maintained test workflow.
    text = text.replace("name: CI\n", "name: Release\n", 1)

    OUT.write_text(text)
    print(f"wrote {OUT} — review the diff before committing.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
